accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.school_admin_register, name="school_admin_register"),
    path("login/", views.school_admin_login, name="school_admin_login"),
    path("logout/", views.logout_view, name="logout_view"),
    # forgot password
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("otp-confirmation/", views.otp_confirmation, name="otp_confirmation"),
    path(
        "set-new-password/<int:user_id>/",
        views.set_new_password,
        name="set_new_password",
    ),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("app.urls")),
    path("school/", include("school.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    address = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=10, null=True, blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", null=True, blank=True)

    def __str__(self):
        return self.username


class OTP(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    otp = models.CharField(max_length=10, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def generate_otp(email, length=8):
        import random

        user = CustomUser.objects.filter(email=email).first()
        if user is None:
            raise Exception("User does not exist")

        # try to generate a unique otp at most 3 times
        for _ in range(3):
            otp = "".join(str(random.randint(0, 9)) for _ in range(length))
            if not OTP.objects.filter(otp=otp).exists():
                break

        new_otp = OTP(user=user, otp=otp)
        new_otp.save()

        return new_otp.otp

    def is_expired(self):
        from django.utils import timezone
        import datetime

        now = timezone.now()
        return now - self.created_at > datetime.timedelta(minutes=10)

    @staticmethod
    def check_otp(otp_value):
        otp_record = OTP.objects.filter(otp=otp_value).first()
        if otp_record and not otp_record.is_expired():  # otp is valid and used
            user_id = otp_record.user.id
            otp_record.delete()
            return user_id
        return None

    def __str__(self):
        return self.otp

accounts/forms.py
from django import forms
from .models import CustomUser
from django.forms import widgets as widget


class SchoolAdminLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Username",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Password",
            }
        )
    )


class SchoolAdminRegisterForm(forms.Form):
    username = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Username",
            }
        ),
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Email",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Password",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Confirm Password",
            }
        )
    )
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "First Name",
            }
        ),
    )
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Last Name",
            }
        ),
    )
    phone_number = forms.CharField(
        max_length=10,
        widget=forms.TextInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Phone",
            }
        ),
    )
    address = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "input w-full p-2 mb-2",
                "placeholder": "Address",
            }
        ),
    )
    profile_pic = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"class": "file-input w-full p-2"}),
        required=False,
    )

    def clean(self):
        if self.cleaned_data["password1"] != self.cleaned_data["password2"]:
            raise forms.ValidationError("Passwords do not match")

        if CustomUser.objects.filter(username=self.cleaned_data["username"]).exists():
            raise forms.ValidationError("Username already exists")

    def save(self, commit=True):
        user = CustomUser(
            username=self.cleaned_data["username"],
            email=self.cleaned_data["email"],
            first_name=self.cleaned_data["first_name"],
            last_name=self.cleaned_data["last_name"],
            phone_number=self.cleaned_data["phone_number"],
            address=self.cleaned_data["address"],
            profile_pic=self.cleaned_data["profile_pic"],
        )
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from .forms import SchoolAdminRegisterForm, SchoolAdminLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .utils import is_email_valid,forgot_password_email,password_changed_email
from .models import OTP, CustomUser
from django.contrib.auth.password_validation import validate_password



def school_admin_register(request):
    if request.method == "POST":
        form = SchoolAdminRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("accounts:school_admin_login")

        context = {"form": form}
        return render(request, "accounts/register.html", context)

    form = SchoolAdminRegisterForm()
    context = {"form": form}
    return render(request, "accounts/register.html", context)


def school_admin_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("app:dashboard")

        messages.error(request, "Invalid username or password")
        return redirect("accounts:school_admin_login")

    form = SchoolAdminLoginForm()

    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("accounts:school_admin_login")


def forgot_password(request):
    if request.method == "POST":
        email = request.POST.get("email")
        
        if not is_email_valid(email):
            messages.error(request, "Invalid email address")
            return redirect("accounts:forgot_password")
        
        try:
            forgot_password_email(email)
            
        except Exception as e:
            messages.error(request, str(e))
            return redirect("accounts:forgot_password")
        
        
        # send otp to email
        print("Code sent successfully to", email)
        messages.success(request, "Code sent successfully !")
        
        return redirect("accounts:otp_confirmation")
    
    return render(request, "accounts/forgot-password.html")


def otp_confirmation(request):
    if request.method == "POST":
        otp = request.POST.get("otp")
        # print(otp,"OTP received")
        user_id = OTP.check_otp(otp)
        
        if user_id is None:
            messages.error(request, "Invalid OTP, Try Again")
            return redirect("accounts:otp_confirmation")
        
        
        return redirect("accounts:set_new_password", user_id=user_id)
    
    return render(request, "accounts/otp-confirmation.html")


def set_new_password(request, user_id=None):
    if request.method == "POST":
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        # send otp to password
        
        if password1 != password2:
            messages.error(request, "Passwords do not match")
            return redirect("accounts:set_new_password")
        
        try:
            validate_password(password1)
        except Exception as e:
            for error in list(e):
                messages.error(request, str(error))
            return redirect("accounts:set_new_password")  
        else:
            if user_id is not None:
                user = CustomUser.objects.get(id=user_id)
                
                if user is None:
                    messages.error(request, "User does not exist")
                    return redirect("accounts:set_new_password")
                   
            user.set_password(password1)
            user.save()
            password_changed_email(user.email)
            return redirect("accounts:school_admin_login")
        
        
        
    return render(request, "accounts/new-password.html")

accounts/templates/accounts/forgot-password.html
{% extends 'base.html' %}


{% block sidebar %}
{% endblock %}


{% block content %}
<div class="w-full flex justify-center align-center p-4">

    <div class="toast toast-end toast-top">
        {% for message in messages %}
        <div class="alert alert-error alert-soft">
            <span>{{message}}</span>
        </div>
        {% endfor %}
    </div>


    <form class="w-1/2 max-w-md flex flex-col p-4  border border-base-300 rounded-box h-[450px] mt-[100px]"
        method="post">
        {% csrf_token %}

        <h1 class="text-3xl font-bold mb-4">Forgot Password</h1>
        <fieldset class="fieldset mb-4">
            <legend class="fieldset-legend">Email</legend>
            <input type="email" name="email" placeholder="Email" required class="input input-bordered w-full ">
        </fieldset>


        <button class=" btn btn-primary" type="submit">Send OTP</button>
        <a href="{% url 'accounts:school_admin_login' %}" class="mt-4 text-sm text-blue-500">
            Remebered your password? Click here to login
        </a>

    </form>
</div>
<!-- Your page content here -->
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block sidebar %}
{% endblock %}


{% block content %}
<div class="w-full flex justify-center align-center p-4">

    <div class="toast toast-end toast-top">
        {% for message in messages %}
        <div class="alert alert-error alert-soft">
            <span>{{message}}</span>
        </div>
        {% endfor %}
    </div>


    <form class="w-1/2 max-w-md flex flex-col p-4  border border-base-300 rounded-box h-[450px] mt-[100px]"
        method="post">
        {% csrf_token %}

        <h1 class="text-3xl font-bold mb-4">LOGIN</h1>

        {% for field in form %}

        <fieldset class="fieldset mb-4">
            <legend class="fieldset-legend">{{field.label}}</legend>
            {{field}}
            {{field.errors}}
        </fieldset>

        {% endfor %}

        <button class="btn btn-primary" type="submit">Login</button>
        <a href="{% url 'accounts:school_admin_register' %}" class="mt-4 text-sm text-blue-500">
            Not a member? Click here to register
        </a>
        <a href="{% url 'accounts:forgot_password' %}" class="mt-4 text-sm text-blue-500">
            Forgot Password?
        </a>
    </form>
</div>
<!-- Your page content here -->
{% endblock %}

accounts/templates/accounts/new-password.html
{% extends 'base.html' %}


{% block sidebar %}
{% endblock %}


{% block content %}
<div class="w-full flex justify-center align-center p-4">
    <div class="toast toast-end toast-top">
        {% for message in messages %}
        <div class="alert alert-error alert-soft">
            <span>{{message}}</span>
        </div>
        {% endfor %}
    </div>

    <form class="w-1/2 max-w-md flex flex-col p-4  border border-base-300 rounded-box h-[450px] mt-[100px]"
        method="post">
        {% csrf_token %}

        <h1 class="text-3xl font-bold mb-4">Set New Password</h1>
        <fieldset class="fieldset mb-4">
            <legend class="fieldset-legend">New Password</legend>
            <input type="password" name="password1" required class="input input-bordered w-full ">
        </fieldset>
        <fieldset class="fieldset mb-4">
            <legend class="fieldset-legend">Confirm New Password</legend>
            <input type="password" name="password2" required class="input input-bordered w-full ">
        </fieldset>


        <button class=" btn btn-primary" type="submit">Set Password</button>
        <a href="{% url 'accounts:school_admin_login' %}" class="mt-4 text-sm text-blue-500">
            Didn't get the OTP? Click here to resend
        </a>

    </form>
</div>
<!-- Your page content here -->
{% endblock %}

accounts/templates/accounts/otp-confirmation.html
{% extends 'base.html' %}


{% block sidebar %}
{% endblock %}


{% block content %}
<div class="w-full flex justify-center align-center p-4">


    <div class="toast toast-end toast-top">
        {% for message in messages %}
        <div class="alert alert-error alert-soft">
            <span>{{message}}</span>
        </div>
        {% endfor %}
    </div>

    <form class="w-1/2 max-w-md flex flex-col p-4  border border-base-300 rounded-box h-[450px] mt-[100px]"
        method="post">
        {% csrf_token %}

        <h1 class="text-3xl font-bold mb-4">OTP confirmation</h1>
        <fieldset class="fieldset mb-4">
            <legend class="fieldset-legend">Enter you OTP</legend>
            <input type="text" name="otp" placeholder="eg. 123456" class="input input-bordered w-full ">
        </fieldset>


        <button class=" btn btn-primary" type="submit">Confirm</button>
        <p class="text-sm text-white">This may take a while, please wait</p>
        <a href="{% url 'accounts:forgot_password' %}" class="mt-4 text-sm text-blue-500">
            Didn't get the OTP? Click here to resend
        </a>

    </form>
</div>
<!-- Your page content here -->
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}


{% block sidebar %}
{% endblock %}


{% block content %}
<div class="w-full flex justify-center p-4">

    <div class="toast toast-end toast-top">
        {% for error in form.non_field_errors %}
        <div class="alert alert-error alert-soft">
            <span>{{error}}</span>
        </div>
        {% endfor %}
    </div>
    <form class="w-1/2 flex flex-col p-4 " method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <fieldset class="fieldset bg-base-200 border-base-300 rounded-box border p-4 text-sm md:text-lg shadow-md ">
            <legend class="fieldset-legend text-2xl">Register</legend>


            {% for field in form %}


            <label class="label">{{field.label}}</label>
            {{field}}

            {% for error in field.errors %}
            <div class="text-red-600 text-sm">
                <span>{{error}}</span>
            </div>
            {% endfor %}

            {% endfor %}




            <button class="btn btn-neutral mt-4">Register</button>


            <a href="{% url 'accounts:school_admin_login' %}" class="mt-4 text-sm text-blue-500">
                Already have an account? Click here to login
            </a>
        </fieldset>

    </form>
</div>
<!-- Your page content here -->
{% endblock %}